version: "3"
services:
  #mysql
  mysql:
    image: mysql:${MYSQL_VERSION}
    networks:
      - mysql
    environment:
      - MYSQL_ROOT_PASSWORD:${MYSQL_PASSWORD}
    volumes:
      - ${MYSQL_LOG}:/logs
      - ${MYSQL_CNF_PATH}:/etc/mysql/my.cnf
    ports:
      - ${MYSQL_PORTS}:3306
  redis:
    image: redis:${REDIS_VERSION}
    volumes:
      - ${REDIS_DATA}:/data
    networks:
      - redis
    ports:
      - ${REDIS_PORT}:6379
  php-fpm7.2:
    build:
      context: ./php7.2
      args:
        - INSTALL_SWOOLE=${INSTALL_SWOOLE}
        - INSTALL_PHPREDIS=${INSTALL_PHPREDIS}
    volumes:
      - ${APPLICATION}:/www
      - ${PHP72_INI_PATH}:/usr/local/etc/php/php.ini
      - ${PHP72_LOGS_PATH}:/phplogs
    networks:
      - nginx
    links:
      - redis
      - mysql
    ports:
        - ${PHP72_FPM_PORT}:9000
  php-fpm5.6:
    build:
      context: ./php5.6
      args:
        - INSTALL_SWOOLE=${INSTALL_SWOOLE}
        - INSTALL_PHPREDIS=${INSTALL_PHPREDIS}
    volumes:
        - ${APPLICATION}:/www
        - ${PHP56_INI_PATH}:/usr/local/etc/php/php.ini
        - ${PHP56_LOGS_PATH}:/phplogs
    networks:
      - nginx
    links:
        - redis
        - mysql
    ports:
      - ${PHP56_FPM_PORT}:9000
    ### NGINX Server #########################################
  nginx:
    build:
      context: ./nginx
      args:
      - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
      - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
      - CHANGE_SOURCE=${CHANGE_SOURCE}
    volumes:
    - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
    - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
    - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
    - ${NGINX_SSL_PATH}:/etc/nginx/ssl
    ports:
    - "${NGINX_HOST_HTTP_PORT}:80"
    - "${NGINX_HOST_HTTPS_PORT}:443"
    networks:
    - nginxs
networks:
  mysql:
    external: false
  redis:
    external: false
  nginx:
    external: false